project_name: blink-cli
builds:
  - env: [CGO_ENABLED=0]
    main: ./cmd/openapi-cli

    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
brews:
  - tap:
      owner: blinkops
      name: blink-openapi-sdk
    homepage: https://www.blinkops.com/
    license: "MIT"
    description: "Awesome CLI for the blink ops platform"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'